spring:
  application:
    name: springboot-shardingjdbc-demo
#Mybatis配置
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.wudimanong.shardingjdbc.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080